### ISSUE TITLE
some errors on AWS  debian12

### ISSUE THREAD

**Issue by HTGZYY** [Websoft9/manufacture#2452]
![accdab1eb34c2edbdffe0673cdf52ab](https://github.com/user-attachments/assets/4a2a0b4c-5007-473d-889f-96ab4467198a)

mysql生产报错
![c0f443f7cee67432fe446117da5a78d](https://github.com/user-attachments/assets/5c3e7bcc-07dc-4b0a-a7bc-cd14e5869750)

odoo生产报错
![ebf82a91f798f3738af490b0d985df0](https://github.com/user-attachments/assets/945c621a-c209-456a-8d44-b07f5d590fa6)

**Comment by HTGZYY** [comment]
模式磁盘空间不足

**Comment by qiaofeng1227** [comment]
debian12的磁盘根目录/dev/sda1设置错误，应该是/dev/xvda

**Comment by chendelin1982** [comment]
fixed
