### ISSUE TITLE
update PHP runtime on AWS

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/manufacture#2597]
### php-apache

- PHP 7.0 Runtime for Web App (LAMP)  replace with PHP8 on ubuntu
- PHP 7.2 Runtime for Web App (LAMP)  replace with PHP8 on debian

- PHP 7.4 Runtime for Web App (LAMP)  replace with PHP7 on ubuntu
- PHP 7.3 Runtime for Web App (LAMP)  replace with PHP7 on debian

- PHP 5.6 Runtime for Web App (LAMP) replace with PHP5 on  ubuntu

- Cloud Native Database for DocumentDB 5.0 (Ubuntu) replace with PHP on  ubuntu

### php-fpm

PHP 5.6 Runtime for Web App (LEMP)  replace with PHP5 with fpm and nginx on ubuntu
PHP 7.0 Runtime for Web App (LEMP)   replace with PHP（all） with fpm and nginx on ubuntu 
PHP 7.1 Runtime for Web App (LAMP)  replace with PHP（all） with fpm and apache on ubuntu

**Comment by morning-tan** [comment]
PHP-apache系列共6款产品全已更新上架

**Comment by morning-tan** [comment]
php-fpm共三款产品已上架
